### ISSUE TITLE
Adding DSA Questions

### ISSUE THREAD

**Issue by bishalshaw-164** [dubey-harshit/My-First-Repo#46]
I would like to add an additional question Could you please assign this issue to me for Hacktoberfest 2024?

**Comment by dubey-harshit** [comment]
Sure!

**Comment by coder483** [comment]
i added a DSA problem please check it please check it and if you find any issue please notify me i'll fix it

**Comment by anshiiJ** [comment]
hi can you please assign me this issue, i would like to add my own problem solving approach !!!

**Comment by Gungunmi12** [comment]
I would like to add my solution to this issue can u please assign it to me
