### ISSUE TITLE
Adding DFS

### ISSUE THREAD

**Issue by Mohitbagul** [dubey-harshit/My-First-Repo#61]
You are given a connected undirected graph. Perform a Depth First Traversal of the graph.
Note: Use the recursive approach to find the DFS traversal of the graph starting from the 0th vertex from left to right according to the graph.

![image](https://github.com/user-attachments/assets/a509e00f-5562-4b1a-ab2b-a0740a1d4519)

![image](https://github.com/user-attachments/assets/f13c279b-84c7-4dff-a93c-6059f2a42153)

**Comment by rajchaudhary99** [comment]
please sign me this issue
